FROM gcc:15

RUN apt-get update && apt-get install -y \
    git \
    make \
    cmake \
    python3-pip \
    python3-setuptools \
    && rm -rf /var/lib/apt/lists/*

# oj をインストール
RUN pip3 install --no-cache-dir online-judge-tools --break-system-packages

WORKDIR /work
